version: "3.3"

services:
  db:
    env_file: ./.env
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - pg_volume:/var/lib/postgresql/data
  app:
    depends_on:
      - db
    build: ./
    env_file: ./.env
    ports:
      - $SPRING_PORT:$SPRING_PORT

volumes:
  pg_volume: