version: "3.3"

services:
  db:
    env_file: ./.env
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - pg_volume:/var/lib/postgresql/data

  
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://:9092,EXTERNAL://:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  config-server:
    env_file: ./.env
    build:
      context: .
      dockerfile: config-server/Dockerfile
    restart: always
    container_name: config-server
    ports:
      - "9999:9999"
    depends_on:
      - db
      - kafka
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - TMDB_API_KEY=$TMDB_API_KEY
      - KAFKA_URL=http://kafka:29092

  eureka-server:
    env_file: ./.env
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    restart: always
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - KAFKA_URL=http://kafka:29092

  gateway:
    env_file: ./.env
    build:
      context: .
      dockerfile: gateway/Dockerfile
    restart: always
    container_name: gateway
    ports:
      - "8765:8765"
    depends_on:
      - db
      - eureka-server
      - config-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - KAFKA_URL=http://kafka:29092

  user-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - WS_SERVER_URL=ws://websocket-service:9898/movieswipper-ws
      - KAFKA_URL=http://kafka:29092
    restart: always
    depends_on:
      - db
      - eureka-server
      - config-server


  auth-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    restart: always
    container_name: auth-service
    depends_on:
      - user-service
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL_R2
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - KAFKA_URL=http://kafka:29092

  movie-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: movie-service/Dockerfile
    restart: always
    container_name: movie-service
    depends_on:
      - user-service
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL_R2
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - TMDB_API_KEY=$TMDB_API_KEY
      - KAFKA_URL=http://kafka:29092

  websocket-service:
    env_file: ./.env
    ports:
      - "9898:9898"
    build:
      context: .
      dockerfile: websocket-service/Dockerfile
    restart: always
    container_name: websocket-service
    depends_on:
      - eureka-server
    environment:
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - KAFKA_URL=http://kafka:29092

  
  file-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: file-service/Dockerfile
    restart: always
    container_name: file-service
    depends_on:
      - eureka-server
    environment:
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - POSTGRES_URL=$POSTGRES_URL_R2
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - KAFKA_URL=http://kafka:29092

  notification-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    restart: always
    container_name: notification-service
    depends_on:
      - eureka-server
    environment:
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - GMAIL_MAIL=$GMAIL_MAIL
      - GOOGLE_APP_PASS=$GOOGLE_APP_PASS
      - WS_SERVER_URL=ws://websocket-service:9898/movieswipper-ws
      - KAFKA_URL=http://kafka:29092

  session-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: session-service/Dockerfile
    restart: always
    container_name: session-service
    depends_on:
      - eureka-server
    environment:
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - KAFKA_URL=http://kafka:29092

volumes:
  pg_volume: