version: "3.3"

services:
  db:
    env_file: ./.env
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    volumes:
      - pg_volume:/var/lib/postgresql/data

  config-server:
    env_file: ./.env
    build:
      context: .
      dockerfile: config-server/Dockerfile
    restart: always
    container_name: config-server
    ports:
      - "9999:9999"
    depends_on:
      - db
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - TMDB_API_KEY=$TMDB_API_KEY

  eureka-server:
    env_file: ./.env
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    restart: always
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka

  gateway:
    env_file: ./.env
    build:
      context: .
      dockerfile: gateway/Dockerfile
    restart: always
    container_name: gateway
    ports:
      - "8765:8765"
    depends_on:
      - db
      - eureka-server
      - config-server
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka

  user-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - WS_SERVER_URL=ws://websocket-service:9898/movieswipper-ws
    restart: always
    depends_on:
      - db
      - eureka-server
      - config-server


  auth-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    restart: always
    container_name: auth-service
    depends_on:
      - user-service
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL_R2
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka

  movie-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: movie-service/Dockerfile
    restart: always
    container_name: movie-service
    depends_on:
      - user-service
    environment:
      - TZ=Europe/Moscow
      - POSTGRES_URL=$POSTGRES_URL_R2
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - TMDB_API_KEY=$TMDB_API_KEY

  websocket-service:
    env_file: ./.env
    ports:
      - "9898:9898"
    build:
      context: .
      dockerfile: websocket-service/Dockerfile
    restart: always
    container_name: websocket-service
    depends_on:
      - eureka-server
    environment:
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka

  
  file-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: file-service/Dockerfile
    restart: always
    container_name: file-service
    depends_on:
      - eureka-server
    environment:
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - POSTGRES_URL=$POSTGRES_URL_R2
      - POSTGRES_USERNAME=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  notification-service:
    env_file: ./.env
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    restart: always
    container_name: notification-service
    depends_on:
      - eureka-server
    environment:
      - CONFIG_URL=http://config-server:9999
      - EUREKA_URL=http://eureka-server:8761/eureka
      - GMAIL_MAIL=$GMAIL_MAIL
      - GOOGLE_APP_PASS=$GOOGLE_APP_PASS
      - WS_SERVER_URL=ws://websocket-service:9898/movieswipper-ws

volumes:
  pg_volume: