spring:
  application:
    name: gateway
  config:
    import: configserver:${CONFIG_URL:http://localhost:9999}
  main:
    web-application-type: reactive
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - ${KAFKA_URL}

logging:
  level:
    web: trace
