spring:
  application:
    name: session-service
  config:
    import: configserver:${CONFIG_URL:http://localhost:9999}
  cloud:
    stream:
      kafka:
        binder:
          brokers:
            - ${KAFKA_URL}
    bus:
      trace:
        enabled: true
      refresh:
        enabled: true
      env:
        enabled: true