CREATE TABLE genre
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    tmdb_genre_id BIGINT,
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

CREATE TABLE genres
(
    genre_id BIGINT NOT NULL,
    user_id  BIGINT NOT NULL,
    CONSTRAINT pk_genres PRIMARY KEY (genre_id, user_id)
);

CREATE TABLE movie_session
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id         BIGINT,
    tmdb_movie_id   BIGINT,
    session_id      BIGINT,
    liked           BOOLEAN,
    CONSTRAINT pk_movie_session PRIMARY KEY (id)
);

CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id)
);

CREATE TABLE roles
(
    role_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id, user_id)
);

CREATE TABLE session
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creator_id  BIGINT,
    invite_code VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_session PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(25),
    password VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_session
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT,
    session_id BIGINT,
    CONSTRAINT pk_user_session PRIMARY KEY (id)
);