server:
  port: 9999
spring:
  kafka:
    bootstrap-servers:
      - ${KAFKA_URL}
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: https://github.com/HackMemory0/movie-swipper-config
          clone-on-start: true
    bus:
      enabled: true
      id: config-server

  #DB
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql: true
    hibernate:
      ddl-auto: none
  #flyway
  flyway:
    locations: classpath:db/migration